### PR TITLE
Mini console

### PR DESCRIPTION
**Pull request by jasonjmcghee**
added the mini console, and the print function! #14

### CODE REVIEW

**Comment by jasonjmcghee** [comment]
@cjdell If you want to pursue the pop-out/split screen, we can decline this.

**Comment by jasonjmcghee** [comment]
@cjdell Hey- any update on your feelings on this?

**Comment by cjdell** [comment]
@jasonjmcghee Just merged this and made a few tweaks too. I hope you approve. :-)

By the way, I'm impressed with all the work you've put into this project. It's great that you believe it's worth your valuable time. I'm very humbled by it all. :-)

**Comment by jasonjmcghee** [comment]
@cjdell nice font ;) I like the way it looks. I made another PR that pulls that object I put together inside that class into it's own class and cleaned everything to look similar to how i did before I jumped in and mucked about. #27 I'm having a great time, don't worry. And thanks for letting me contribute! Many people are incredibly protective of their ideas/projects, so I really appreciate you trusting my input/contributions. I have a number of ideas that I'm excited to suggest, but the more I contribute the stronger I see the need for tests, but I keep putting them off. Hopefully I'll get my act together here soon 😛

**Pull request merged**
