### PR TITLE
improved the cli

### PR DESCRIPTION
**Pull request by jasonjmcghee**
Before:image
After:image

### CODE REVIEW

**Comment by jasonjmcghee** [comment]
Improved is a strong word. All I did was attempt to pass it through the cli _not_ inside of the `return` statement, should it fail. Oh I also strip out `var` and `;` before trying it outside of `return`, so that you'd see it's output like in the browser interpreter. If you see anything wrong with this method, feel free to modify/decline. Seemed like a good addition to me though.

**Comment by jasonjmcghee** [comment]
Now you can write a few scripts and bind them to some numbers and run them as much as you want! No more one script at a time.

**Comment by jasonjmcghee** [comment]
Alright this PR is big enough :)

Edit: Okay, one more, but I need to leave for work!

**Comment by cjdell** [comment]
@jasonjmcghee I was a bit trigger happy merging this in. Turns out that two files are missing:

samples/BoundPillar.js
samples/MouseBlock.js

Other than that it looks good. :-)

**Comment by jasonjmcghee** [comment]
Ah! Didn't see that `*.js` was in the `.gitignore`! My fault. Made new PR with said update.

**Pull request merged**
